const MAALTIJDEN = [
  {
    id: 99,
    type: "warmeMaaltijd",
    leverdatum: "2023-10-07T00:00:00.000Z",
    hoofdschotel: "lasagne",
    soep: true,
    dessert: "zuivel",
    typeSandwiches: null,
    hartigBeleg: null,
    zoetBeleg: null,
    vetstof: null,
    suggestieVanDeMaandId: null,
  },
  {
    id: 100,
    type: "broodMaaltijd",
    leverdatum: "2023-10-08T00:00:00.000Z",
    hoofdschotel: null,
    typeSandwiches: "bruin",
    hartigBeleg: "hesp",
    zoetBeleg: "choco",
    vetstof: true,
    soep: false,
    dessert: "fruit",
    suggestieVanDeMaandId: null,
  },
  {
    id: 101,
    type: "warmeMaaltijd",
    leverdatum: "2023-10-07T00:00:00.000Z",
    hoofdschotel: "suggestie",
    soep: true,
    dessert: "fruit",
    typeSandwiches: null,
    hartigBeleg: null,
    zoetBeleg: null,
    vetstof: null,
    suggestieVanDeMaandId: 1,
  },
  {
    id: 102,
    type: "broodMaaltijd",
    leverdatum: "2023-10-09T00:00:00.000Z",
    hoofdschotel: null,
    typeSandwiches: "wit",
    hartigBeleg: "kaas",
    zoetBeleg: "speculoos",
    vetstof: false,
    soep: true,
    dessert: "zuivel",
    suggestieVanDeMaandId: null,
  },
];

export default MAALTIJDEN;
